spring:
  application:
    name: eureka
server:
  port: 7900
eureka:
  instance:
    hostname: eureka01
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    enable-self-preservation: false # 关闭自我保护
    eviction-interval-timer-in-ms: 1000 # 快速下线
    use-read-only-response-cache: false # 不使用缓存
---
spring:
  profiles: eureka01
eureka:
  instance:
    hostname: eureka01

---
spring:
  profiles: eureka02
eureka:
  instance:
    hostname: eureka02

---
spring:
  profiles: eureka03
eureka:
  instance:
    hostname: eureka03